"""
Table Processor.

For every TABLE chunk, prepend a short natural-language description
generated by the text LLM.  This improves semantic retrieval because
markdown tables alone are not very dense in meaning for embedding models.
"""

from __future__ import annotations

import asyncio
from typing import List

from langchain_core.messages import HumanMessage, SystemMessage

from config.settings import settings
from core.llm import get_llm
from models.document import DocumentChunk, Modality

_MAX_CONCURRENT = 4
_TABLE_PROMPT = (
    "You are a data analyst assistant. "
    "Given the following Markdown table, write a concise 2-3 sentence description that:\n"
    "1. Explains what the table represents\n"
    "2. Highlights the most important values or trends\n"
    "3. Notes the column headings and approximate row count\n\n"
    "Respond with ONLY the description — no preamble, no markdown formatting.\n\n"
    "Table:\n{table}"
)


class TableProcessor:
    """Add a natural-language description to every TABLE chunk."""

    async def process(self, chunks: List[DocumentChunk]) -> List[DocumentChunk]:
        table_chunks = [c for c in chunks if c.modality == Modality.TABLE]
        other_chunks = [c for c in chunks if c.modality != Modality.TABLE]

        if not table_chunks:
            return chunks

        semaphore = asyncio.Semaphore(_MAX_CONCURRENT)
        tasks = [self._describe(chunk, semaphore) for chunk in table_chunks]
        enriched = await asyncio.gather(*tasks, return_exceptions=True)

        result = list(other_chunks)
        for original, enriched_or_exc in zip(table_chunks, enriched):
            if isinstance(enriched_or_exc, Exception):
                print(f"[TableProcessor] Description failed: {enriched_or_exc}")
                result.append(original)
            else:
                result.append(enriched_or_exc)
        return result

    async def _describe(
        self, chunk: DocumentChunk, semaphore: asyncio.Semaphore
    ) -> DocumentChunk:
        async with semaphore:
            llm = get_llm()
            prompt = _TABLE_PROMPT.format(table=chunk.content[:3000])
            response = await llm.ainvoke([HumanMessage(content=prompt)])
            description = (
                response.content if isinstance(response.content, str) else str(response.content)
            )
            # Prepend description so the embedding captures semantic meaning
            enriched_content = f"{description}\n\n{chunk.content}"
            return chunk.model_copy(update={"content": enriched_content})
